/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package Walker.model.transform;

import javax.xml.bind.JAXBException;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.parser.Feature;
import com.jdcloud.sdk.JdcloudSdkException;
import com.jdcloud.sdk.http.ContentType;
import com.jdcloud.sdk.service.JdcloudUnmarshaller;
import com.jdcloud.sdk.utils.ConvertUtils;
import Walker.model.POSTResponse;

public class POSTResponseUnmarshaller implements JdcloudUnmarshaller {

    public final static Feature[] FEATURES = { Feature.AutoCloseSource, Feature.UseBigDecimal,
            Feature.AllowUnQuotedFieldNames, Feature.AllowSingleQuotes, Feature.AllowArbitraryCommas,
            Feature.AllowArbitraryCommas, Feature.SortFeidFastMatch, Feature.IgnoreNotMatch };

    public POSTResponse unmarshall(String content, ContentType contentType) {
        POSTResponse pOSTResponse = new POSTResponse();
        if(contentType == ContentType.APPLICATION_XML || contentType == ContentType.TEXT_XML) {

            try {
                pOSTResponse.setResult(content);
            } catch (Exception e) {
                throw new JdcloudSdkException(e);
            }

        } else {
            pOSTResponse.setResult(content);}
        return pOSTResponse;
    }

    private static POSTResponseUnmarshaller instance;

    public static POSTResponseUnmarshaller getInstance() {
        if (instance == null)
            instance = new POSTResponseUnmarshaller();
        return instance;
    }
}