/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package Walker.model;

import com.jdcloud.sdk.service.JdcloudResponse;
import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;
import java.io.IOException;
import javax.xml.bind.annotation.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * POSTResponse
 */
@XmlRootElement(name = "pOST_response")
@XmlAccessorType(XmlAccessType.FIELD)

public class POSTResponse extends JdcloudResponse implements Serializable {

    private static final long serialVersionUID = 1L;

    private String result = null;

    public POSTResponse result(String result) {
        this.result = result;
        return this;
    }

    /**
     * Get result
     * @return result
     **/

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }


}

