/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */
package Walker.client;

import com.jdcloud.sdk.JdcloudSdkException;
import com.jdcloud.sdk.auth.CredentialsProvider;
import com.jdcloud.sdk.client.Environment;
import com.jdcloud.sdk.client.Jdcloud;
import com.jdcloud.sdk.client.JdcloudClient;
import com.jdcloud.sdk.client.JdcloudValidateException;
import com.jdcloud.sdk.http.HttpRequestConfig;
import Walker.model.*;

/**
 * https://wko7luloi5tj.cn-north-1.jdcloud-api.net
 */
public class LingCutoutGroupClient extends JdcloudClient {

    public final static String ApiVersion = "";
    private final static String UserAgentPrefix = "JdcloudSdkJava";
    public final static String ClientVersion = "2.1.0";
    public final static String DefaultEndpoint = "wko7luloi5tj.cn-north-1.jdcloud-api.net";
    public final static String ServiceName = "wko7luloi5tj";
    public final static String UserAgent = UserAgentPrefix + "/" + ClientVersion + " " + ServiceName + "/" + ApiVersion;
    public final static String REGION_ID = "cn-north-1";

    CredentialsProvider credentialsProvider;
    HttpRequestConfig httpRequestConfig;
    Environment environment = new Environment.Builder().endpoint(DefaultEndpoint).build();

    public CredentialsProvider getCredentialsProvider() {
        return credentialsProvider;
    }

    public HttpRequestConfig getHttpRequestConfig() {
        return httpRequestConfig;
    }

    public Environment getEnvironment() {
        return environment;
    }

    public String getUserAgent() {
        return UserAgent;
    }

    public String getServiceName() {
        return ServiceName;
    }

    public String getVersion() {
        return ApiVersion;
    }

    public String getRegionId() {
        return REGION_ID;
    }

    private LingCutoutGroupClient() {

    }

    public static Builder builder() {
        return new DefaultBuilder();
    }

    public interface Builder {
        public Builder credentialsProvider(CredentialsProvider provider);
        public Builder environment(Environment environment);
        public Builder httpRequestConfig(HttpRequestConfig config);
        public LingCutoutGroupClient build() throws JdcloudSdkException;
    }

    private static class DefaultBuilder implements Builder {

        private LingCutoutGroupClient LingCutoutGroupClient;

        public DefaultBuilder() {
            LingCutoutGroupClient = new LingCutoutGroupClient();
        }

        public DefaultBuilder credentialsProvider(CredentialsProvider provider) {
            LingCutoutGroupClient.credentialsProvider = provider;
            return this;
        }

        public DefaultBuilder httpRequestConfig(HttpRequestConfig config) {
            LingCutoutGroupClient.httpRequestConfig = config;
            return this;
        }

        public LingCutoutGroupClient build() throws JdcloudSdkException {

            if (LingCutoutGroupClient.credentialsProvider == null) {
                //if credentialsProvider not set, try load jdcloud global default  credentials provider
                LingCutoutGroupClient.credentialsProvider = Jdcloud.defaultInstance().getCredentialsProvider();
            }
            if (LingCutoutGroupClient.httpRequestConfig == null) {
                LingCutoutGroupClient.httpRequestConfig = Jdcloud.defaultInstance().getHttpRequestConfig();
                if (LingCutoutGroupClient.httpRequestConfig == null) {
                    throw new JdcloudValidateException("LingCutoutGroupClient build error: http request config not set");
                }
            }
            return LingCutoutGroupClient;
        }

        public Builder environment(Environment environment) {
            LingCutoutGroupClient.environment = environment;
            return this;
        }
    }


    /**
     *
     *
     * @param request
     * @return
     * @throws JdcloudSdkException
     */
    public POSTResponse pOST(POSTRequest request) throws JdcloudSdkException {
        return new POSTExecutor().client(this).execute(request);
    }


}
